name: admin
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  csv: ^6.0.0
  dropdown_search: ^5.0.6
  firebase_core: ^3.1.0
  flex_color_scheme: ^7.3.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_dotenv: ^5.1.0
  flutter_email_sender: ^6.0.3
  flutter_rating_bar: ^4.0.1
  flutter_secure_storage: ^9.2.2
  http: ^1.2.1
  intl: ^0.19.0
  mailer: ^6.1.0
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  two_dimensional_scrollables: ^0.3.1
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

assets:
  - .env